# Generated by Django 5.0.6 on 2024-08-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Course',
        ),
    ]
