# Generated by Django 5.0.6 on 2024-08-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_product_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_paid',
            new_name='enrolled',
        ),
    ]
