# Generated by Django 5.0.6 on 2024-08-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_course_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
